name: Pruebas HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar prueba unitaria
      run: npm test
